name: E2E Tests

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "development", "master" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app
        run: npm run start & sleep 5

      - name: Install Cypress
        run: npm install cypress

      - name: Run Cypress E2E tests
        run: npx cypress run --headless
